### ISSUE TITLE
I/O error on RX50 (MSCP) after detach and attach

### ISSUE THREAD

**Issue by pkoning2** [open-simh/simh#65] opened 2022-09-24 18:58 UTC
PDP11 emulation running RSTS V10.1.  I can attach an RX50 image and mount it, but if I then unmount it, detach, attach a different image, attempting to mount that second image results in a SIMH failure:
```
sim> det rq3
sim> att -3 rq3 ../svn/flx/floppies/m3.dsk 
%SIM-INFO: RQ3: '../svn/flx/floppies/m3.dsk' Contains a RSTS File system
%SIM-INFO: RQ3: Pack ID: MICR3  Revision Level: 1.2 Pack Clustersize: 1
%SIM-INFO: RQ3: Last Unallocated Sector In File System: 798
sim> c
mou du3: /over/nowr
RQ I/O error: Unknown error: 316
                                RQ3 RQ I/O error: Unknown error: 316

%SIM-ERROR: Unexpected internal error while processing event for RQ3 which returned 66 - I/O error

I/O error, PC: 100640 (BR 100630)
sim> c
?Device hung or write locked
```
I see this on a version I built back in July, so it's been around at least for a little while.

**Comment by pkoning2** [comment] 2022-09-25 20:53
FWIW, I tried this on the V3 version and it doesn't have the problem.  Has the RQ emulation changed?  If not then it points the finger of suspicion at sim_disk.
I find it curious to see an error reported by stopping the simulation.  Normally I'd expect them to be turned into errors seen by the emulated device.

**Comment by pkoning2** [comment] 2022-09-27 00:48
When I hack the makefile to disable the ASYNC stuff, it still fails but with a different message.  I now see:
```
RQ I/O error: Bad address
                         RQ3 RQ I/O error: Bad address

%SIM-ERROR: Unexpected internal error while processing event for RQ3 which returned 66 - I/O error
```

**Comment by pkoning2** [comment] 2022-09-27 23:58
This was also just reported in the MicroVAX simulator.

**Comment by markpizz** [comment] 2022-09-28 00:01
This is a duplicate of #15 reported and fixed in https://github.com/simh/simh back on June 16

**Comment by pkoning2** [comment] 2022-09-28 00:10
I guess it isn't actually fixed because I encountered it on today's SIMH.

**Closed** 2023-07-17 13:14 UTC
