### ISSUE TITLE
vax780: segfault on saving state

### ISSUE THREAD

**Issue by DNied** [open-simh/simh#60] opened 2022-09-20 23:41 UTC
- #### Context
Saving the emulator's state with `save foo` (at the `simh>` prompt) segfaults and produces a (corrupt?) file that will make the emulator segfault on a subsequent launch when trying to restore state with `restore foo`.

- #### output of "sim> SHOW VERSION"
```
+sim> show version
VAX 11/780 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:TAP:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 8.3.0
        Simulator Compiled as C arch: x64 (Release Build) on Sep 20 2022 at 00:20:56
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.39 2016-06-14) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        Ethernet packet info: libpcap version 1.8.1
        OS: Linux localhost 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64 GNU/Linux
        Processor Name: AMD E1-2100 APU with Radeon(TM) HD Graphics
        tar tool: tar (GNU tar) 1.30
        curl tool: curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1n zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
        simh git commit id: 84bf5f4d
        simh git commit time: 2022-09-19T09:37:17-07:00
```
- #### how you built the simulator or that you're using prebuilt binaries
SIMH built from sources downloaded from GitHub. Make's output: [mk-vax780.log](https://github.com/open-simh/simh/files/9611833/mk-vax780.log)

- #### the simulator configuration file (or commands) which were used when the problem occurred.

[vax780.txt](https://github.com/open-simh/simh/files/9611852/vax780.txt)

**Comment by markpizz** [comment] 2022-09-21 16:49
Thanks for the complete and thus easily reproducible problem report.  

After the PR has been merged, please confirm that the problem is fixed and then close the issue.

**Closed** 2022-09-21 17:02 UTC

**Comment by DNied** [comment] 2022-09-21 23:08
I confirm that vax780 now saves and restores state correctly. Thank you for the prompt fix.
