### ISSUE TITLE
Status of branch Supnik-Current and SimH Release V3.12-3

### ISSUE THREAD

**Issue by wfjm** [open-simh/simh#159] opened 2023-01-09 14:51 UTC
SimH V3.12-3 was released on December 12th, see [simh@groups.io](https://groups.io/g/simh/topic/95623877).  
The branch `Supnik-Current`, which so far tracked "SimH Classic" hasn't caught up yet.  
Are there plans to first catch up with the branch and later integrate the updates ?

**Comment by pkoning2** [comment] 2023-01-31 14:55
I submitted the merge into Supnik-Current yesterday and Bob approved and committed it.  Merge into main branch is next.

**Closed by pkoning2** 2023-01-31 14:55 UTC

**Comment by wfjm** [comment] 2023-01-31 15:32
@pkoning2 : thanks !!  
It also be great to tag this commit, as was done before for Bob's releases, see  
  https://github.com/open-simh/simh/tags

And talking of tags: @tlhackque: the tag name 'open-simh' isn't what one would call a _telling name_.

**Comment by tlhackque** [comment] 2023-01-31 16:03
@wfjm - Yes, as the tag annotation notes, it was intended to be "open-simh-baseline" -- that is a convenient tag for the state at the fork.  It's always helpful to have a marker for significant events; the fork seemed as significant as a release.

I added the intended tag, but left the shortened one in place.

Thanks for calling this to my attention.

**Comment by pkoning2** [comment] 2023-01-31 16:19
I added tag v3.12-3.
